helloServiceUri: http://hello-service/
spring.application.name : ${vcap.application.name}
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.name}